import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/react-query-provider";
import NextAuthProvider from "@/providers/next-auth-provider";
import SsgoiProvider from "@/providers/ssgoi-provider";
import localFont from "next/font/local";
import { Suspense } from "react";

const suit = localFont({
  src: "./fonts/SUIT-Variable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-suit",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={suit.variable}>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <Suspense fallback={<div>Loading...</div>}>
            <ReactQueryProvider>
              <SsgoiProvider>{children}</SsgoiProvider>
            </ReactQueryProvider>
          </Suspense>
        </NextAuthProvider>
      </body>
    </html>
  );
}
