import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/react-query-provider";

import { AuthProvider } from "@/providers/auth-provider";
import { CommonModal } from "@/components/shared/common-modal";
import { ReportModal } from "@/components/shared/report-modal";
import localFont from "next/font/local";
import { Suspense } from "react";

const suit = localFont({
  src: "./fonts/SUIT-Variable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-suit",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={suit.variable}>
      <head>
        <script
          src="https://developers.kakao.com/sdk/js/kakao.js"
          async
        ></script>
      </head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<div>Loading...</div>}>
          <ReactQueryProvider>
            <AuthProvider>
                {children}
                <CommonModal />
                <ReportModal />
            </AuthProvider>
          </ReactQueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
